version: 0.2

phases:
  build:
    commands:
      - echo "Starting build"
      - npm install
      - npm install -g sonarqube-scanner
      - npm run build
      - sonar-scanner
      - echo "Sending SES email"
      - aws ses send-email --from "$SES_FROM" --destination "ToAddresses=$SES_TO" --message '{"Subject":{"Data":"SES Test Email"},"Body":{"Text":{"Data":"Hello from AWS CodeBuild"}}}'
