sonar.projectKey=bhushanbihani_learnnodejscodepipeline
sonar.organization=bhushanbihani
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=https://sonarcloud.io
